### ISSUE TITLE
Cannot invoke 'sysctl' in swift 1.2

### ISSUE THREAD

**Issue by pimeo** [InderKumarRathore/DeviceGuru#1]
Hey,

With the 1.2 new Swift version using your lib, I have this error:

`Cannot invoke 'sysctl' with an argument list of type '(inout [Int32], Int, inout [(CChar)], inout UInt, inout [Int32], Int)'`

for this block of code: 

```
var name: [Int32] = [CTL_HW, HW_MACHINE]
var size: UInt = 2
sysctl(&name, 2, nil, &size, &name, 0)
var hw_machine = [CChar](count: Int(size), repeatedValue: 0)
sysctl(&name, 2, &hw_machine, &size, &name, 0)
```

I tried to fix it ... without success. Can you see what is the problem?
Thanks

**Comment by InderKumarRathore** [comment]
@pimeo I have done the changes 486ddff1936a34e5af706492748f2aa14464e4ac you can take the latest code.
Thanks for reporting.

**Comment by InderKumarRathore** [comment]
@pimeo I have changed the code so that we can use this library as a pod.

**Comment by pimeo** [comment]
Thanks !
