### ISSUE TITLE
Bump version for SPM to include iPhone 13

### ISSUE THREAD

**Issue by pnome** [InderKumarRathore/DeviceGuru#101]
I was using the 'iPhone13Family' branch because it had the iPhone 13 devices in it. That branch has now been removed, but SPM can only seem to find version 7.0.1 and not 7.0.3

I believe 7.0.3 is the version that includes iPhone 13 devices.

Hoping this is a quick fix.
Thanks,
Joe

**Comment by InderKumarRathore** [comment]
Hey the 7.0.3 version is already pushed, plz check the tags in repo. Reset the cache in your project because I can add latest version in TestApp.

**Comment by pnome** [comment]
Hi,
Thanks for the quick response. I tried everything I can think of and it's still not finding it.
See what I did here - https://www.loom.com/share/24f5c96db1f54bfc82e229db4c7de6c4

Is there something I'm missing?

**Comment by InderKumarRathore** [comment]
That looks strange. Can you remove the DeviceGuru package and re add it. Also if you could, then please try to use it new project.
I tried different scenarios to reproduce it but couldn't do it.

**Comment by InderKumarRathore** [comment]
Meanwhile if nothing works then you can use master branch. It should have latest code

**Comment by InderKumarRathore** [comment]
Just noticed that you're using a fork of original repository. Please use this url instead 

**https://github.com/InderKumarRathore/DeviceGuru**


![image](https://user-images.githubusercontent.com/352443/146645294-4abd1e95-61aa-4bad-8f12-491918c4d138.png)

**Comment by pnome** [comment]
Thank you!
