### ISSUE TITLE
Device name consistancy

### ISSUE THREAD

**Issue by alpha0010** [InderKumarRathore/DeviceGuru#102]
There seems to be a wide variety of styles selected to name devices.  Are you interested in me preparing a PR to make this more uniform?  Naming scheme selected to be similar to appearance in Apple.

Some examples:

- *Current*
  - *Recommended*
- iPad Air 3 (Wi-Fi)
  - iPad Air (3rd generation)
- iPad (8th generation) WiFi+Cellular
  - iPad (Wi-Fi + Cellular, 8th generation)
- iPad Mini Retina (WiFi)
  - iPad mini 2
- iPad Mini 3 (Wi-Fi + Cellular)
  - iPad mini 3 (Wi-Fi + Cellular)
- iPad Pro 12.9-Inch (Wi-Fi Only - 2nd Gen)
  - iPad Pro 12.9-inch (2nd generation)
- iPad 9.7-Inch 6th Gen (Wi-Fi Only)
  - iPad 9.7-inch (6th generation)
- iPad Pro 12.9-Inch 1TB (Wi-Fi Only - 3rd Gen)
  - iPad Pro 12.9-inch (1TB, 3rd generation)
- iPhone XS Max China
  - iPhone XS Max (China)
- iPod Touch (6 Gen)
  - iPod touch (6th generation)

**Comment by InderKumarRathore** [comment]
Looks neat, go ahead. Please update the generator plist and then run the script to automatically generate the code
