### ISSUE TITLE
iPhone SE (3rd Gen) is not listed

### ISSUE THREAD

**Issue by pirklbauer31** [InderKumarRathore/DeviceGuru#104]
When running the DeviceGuru Library in my App on the iPhone SE (3rd Generation) Simulator I got the following Log output:

```
This is a device which is not listed in this library. Please visit https://github.com/InderKumarRathore/DeviceGuru and submit the issue there.

Your device hardware string is|iPhone14,6|"
```

I am running Version 8.0.0 of the Device Guru Library via Cocoapods.

I hope i didn't miss an already open issue on this topic!

**Comment by InderKumarRathore** [comment]
Thanks for adding it. Will update the list and create new version

**Comment by InderKumarRathore** [comment]
latest changes pushed to 8.0.1

**Comment by pirklbauer31** [comment]
Thanks for the update!
