### ISSUE TITLE
Provide Objective-C examples?

### ISSUE THREAD

**Issue by cliffjoyce** [InderKumarRathore/DeviceGuru#105]
I've been using DeviceUtil which is being replaced by DeviceGuru.

Sadly, I'm not a Swift guru, so am hoping someone can provide examples on how to use DeviceGuru in my Objective-C project.  Thanks.

**Comment by InderKumarRathore** [comment]
I've no intention to support objective-c, but this question is more related to swift.
Here is how you can use any swift code/class in objective-c

First create a swift class

```
@objc class DeviceGuruObjc: NSObject {

    private let deviceGuru = DeviceGuruImplementation()
    @objc func hardwareDescription() -> String? {
        try? deviceGuru.hardwareDescription()
    }
}
```

Usage
```
// This import file should be present in your project after bridging header (I assume)
// This file is named as `YourTarget-Swift.h`
#import "ObjcTestApp-Swift.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    DeviceGuruObjc *deviceGuru = [DeviceGuruObjc new];
    NSLog([deviceGuru hardwareDescription]);
}

@end
```

**Comment by cliffjoyce** [comment]
Thanks so much for this help!

In case it helps any other Swift newbies, I created a new source code file called 'DeviceGuruObjc.swift', and added that to my project.  Here is the contents of the DeviceGuruObjc.swift file:

import Foundation

@objc class DeviceGuruObjc: NSObject {

	private	let	deviceGuru	= DeviceGuruImplementation()

	@objc func hardwareDescription() -> String? {
		try? deviceGuru.hardwareDescription() // like 'iPad Pro 9.7-inch (Wi-Fi + Cellular)'
	}
	
	@objc func hardwareString() -> String? {
		return deviceGuru.hardwareString // like 'iPad6,4'
	}
}

**Comment by cliffjoyce** [comment]
For other Swift newbies...

I added all the DeviceGuru source files to my project, and added these includes to my Objective-C '.m' files where I wanted to call DeviceGuruObjc:

`#import "MyProjectName-Swift.h" // provides access to Swift classes like DeviceGuru`

Then to call DeviceGuruObjc's two functions, I did this:

`DeviceGuruObjc *deviceGuru = [DeviceGuruObjc new];`
`NSLog([deviceGuru hardwareDescription]);` // like 'iPad Pro 9.7-inch (Wi-Fi + Cellular)'
`NSLog([deviceGuru hardwareString]);` // like 'iPad6,4'

**Comment by InderKumarRathore** [comment]
Thank for more information
