### ISSUE TITLE
New iPhone 14 devices

### ISSUE THREAD

**Issue by valentary** [InderKumarRathore/DeviceGuru#107]
Hello, is it possible to update with the latest iPhone 14 devices?

Thanks

**Comment by pnome** [comment]
I'm waiting for this too. Thanks.

**Comment by InderKumarRathore** [comment]
Do you folks has the identifiers of 14 series? Otherwise I have to get it through online

**Comment by InderKumarRathore** [comment]
https://www.everymac.com this shows id is pending 
If you guys have access to this data do let me know or raise a PR

**Comment by valentary** [comment]
I have the ids for the iPhone 14 Pro and iPhone 14 Pro Max

iPhone 14 Pro : 'iPhone15,2'
iPhone 14 Pro Max : 'iPhone15,3'

**Comment by pnome** [comment]
If I print out `DeviceGuruImplementation().hardwareString` when running on iPhone 14 Pro simulator it tells me 'iPhone15,2'
If I do it for iPhone 14 Plus it tells me 'iPhone14,8'
For iPhone 14 it tells me 'iPhone14,7'
Where are these coming from? Would they be the same for the physical devices?

**Comment by InderKumarRathore** [comment]
Yes the simulator and real device gives the same string. And I have added all 14 series to version `10.0.1`
