### ISSUE TITLE
backCameraStillImageResolutionInPixels switch statement has IPHONE_6S twice

### ISSUE THREAD

**Issue by neilt** [InderKumarRathore/DeviceGuru#11]
in DeviceGuru.swift in the function backCameraStillImageResolutionInPixels() the switch statement has cases IPHONE_6S and IPHONE_6S_PLUS mentioned twice (line 251 and line 269) with two different resolutions.  Of course the 2nd case will never be returned.

**Comment by InderKumarRathore** [comment]
Removed, I guess the resolution seems different, I need to test these resolution for portrait mode. Will update the resolutions. Till the keep open this as a bug
