### ISSUE TITLE
DeviceList.plist not found when import via Carthage

### ISSUE THREAD

**Issue by teerapap** [InderKumarRathore/DeviceGuru#111]
Hi

I was using DeviceGuru v7.0.3.  Now I'm upgrading to DeviceGuru v10.0.2 and found a problem.

When I call `try DeviceGuruImplementation().hardwareDescription()`

It throws this error `deviceNotPresentInThePlist("iPhone13,2")`

I debug and found that `DeviceList.plist` is not found anywhere.   It is not included in the built xcramework at `Carthage/Build/DeviceGuru.xcframework`

Thanks

**Comment by InderKumarRathore** [comment]
Thanks for raising it, I have not worked with `Carthage` and someone raise PR to make this lib compatible with `Carthage`. I don't have much experience but if you can fix this and raise a PR that would be nice. Can you try with a sample project

**Comment by teerapap** [comment]
@InderKumarRathore ok. noted. I'll submit a PR later. Thanks.
