### ISSUE TITLE
Instalation with too many instructions

### ISSUE THREAD

**Issue by lfarah** [InderKumarRathore/DeviceGuru#17]
##### Installation

Go to [http://cocoapods.org](http://cocoapods.org) <br>
Search for `DeviceGuru` lib <br>
Copy the pod dependency and add that to your pod file. e.g.

``` sh
pod 'DeviceGuru', '~> x.y'
```
#### I tested just with this line and it worked:

``` sh
pod 'DeviceGuru'
```

**Comment by InderKumarRathore** [comment]
That will also work, but it will install the latest version of the pod. At times you need to freeze the library version to work with your project. the versioning works like this 
major.minor.bug_fixes
If the last version is 1.2.3
and the new one is 1.2.4
it means the new version has some bug fixes, similarly if the new version has minor changes the it will be like 1.3.0
It's your coding style

**Comment by lfarah** [comment]
I get what you're talking about, but for devs who are starting to use CocoaPods, this might be too overwhelming.
I took a look at some libs and that's what I found out:
- [BluetoothKit](https://github.com/rasmusth/BluetoothKit) - `pod 'BluetoothKit', '~> 0.2.0'`
- [ENSwiftSideMenu](https://github.com/evnaz/ENSwiftSideMenu) - `pod 'ENSwiftSideMenu', '~> 0.1'`
- [Prephirences](https://github.com/phimage/Prephirences) - `pod 'Prephirences'`

They make it really easy for the dev to copy and paste in the Pods file. The devs who need to freeze the library already know what they're doing, so they don't need anything on the `README.md.`

**Comment by InderKumarRathore** [comment]
:+1: done changes
