### ISSUE TITLE
Real number in DeviceList.plist

### ISSUE THREAD

**Issue by Rool** [InderKumarRathore/DeviceGuru#23]
Too lazy to make a pull request, but the DeviceList.plist contains:

`  
<dict>
        <key>version</key>

```
    <real>8.199999999999999</real>

    <key>name</key>

    <string>iPhone 6s Plus</string>

</dict>`
```

**Comment by InderKumarRathore** [comment]
Fixed, although 8.2 in floating point is represented as 8.19999999999999
