### ISSUE TITLE
xcode 7.3 support for Carthage

### ISSUE THREAD

**Issue by howie-misfit** [InderKumarRathore/DeviceGuru#24]
I am using carthage and xcode 7.3, when i build it with carthage, it said:

**\* Skipped building DeviceGuru due to the error:
Dependency "DeviceGuru" has no shared framework schemes

Do you have plan for support carthage for xcode 7.3?

**Comment by InderKumarRathore** [comment]
Never used Carthage and I read the document, I need more info to make this repo compatible with the Carthage

**Comment by Jeehut** [comment]
I just pushed a PR which fixes this issue for the iOS platform. If you want to install it via Carthage before it is merged, you can use my fork directly in your Cartfile:

```
github "Dschee/DeviceGuru" "master"
```

**Comment by InderKumarRathore** [comment]
Thanks @Dschee  for taking time to do it. Only readme file is left to be updated on Carthage
