### ISSUE TITLE
swift 3 

### ISSUE THREAD

**Issue by seawolf86** [InderKumarRathore/DeviceGuru#25]
please update for swift 3

**Comment by lfarah** [comment]
I just updated for Swift 3, but @InderKumarRathore has to create a `swift-3` branch first.
[Here's the code](https://gist.github.com/lfarah/59e188af09f9dcbe2960805a3989481e) for now.

**Comment by InderKumarRathore** [comment]
Use below for swift 3 

`pod 'DeviceGuru', '2.0.0.beta.1'
`
