### ISSUE TITLE
how to get device token 64?

### ISSUE THREAD

**Issue by leancmscn** [InderKumarRathore/DeviceGuru#26]
how to get device token 64?

**Comment by InderKumarRathore** [comment]
Do you mean device token for push notification?
If that's so then this lib doesn't provide that. For [APNS read their guideline](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html)

**Comment by leancmscn** [comment]
yes.
