### ISSUE TITLE
iPhone9.3 & 9.4 也是是iPhone和iPhone7 Plus?

### ISSUE THREAD

**Issue by szmichaelyb** [InderKumarRathore/DeviceGuru#33]
iPhone9.3 & 9.4 也是是iPhone和iPhone7 Plus?
![image](https://cloud.githubusercontent.com/assets/9857312/18898920/7d87e64e-8567-11e6-8438-c691239ff9cd.png)

**Comment by InderKumarRathore** [comment]
iPhone9,2和iPhone9,4是iphone 7 plus
