### ISSUE TITLE
1.4.0 CocoaPods

### ISSUE THREAD

**Issue by iwllyu** [InderKumarRathore/DeviceGuru#35]
I get 

[!] Unable to satisfy the following requirements:

- `DeviceGuru (= 1.4.0)` required by `Podfile`

when trying to install DeviceGuru 1.4.0 with CocoaPods. Previously I had 1.3.5. I want to pick up the iPhone7 definitions but cannot upgrade to ~2.0.0 yet. I can pull in 1.3.5 or the latest but it won't let me put 1.4.0

edit: I should add this is with CocoaPods 0.39.0 - My project gets linker errors when I use the latest cocoapods, unfortunately =(

**Comment by InderKumarRathore** [comment]
Can you try `pod 'DeviceGuru', '~> 2.0'`

**Comment by InderKumarRathore** [comment]
Why can't you use `2.0` it's because of swift3 ?

**Comment by iwllyu** [comment]
sorry for the late response - yes.

But I'll be upgrading to swift3 probably within the next month so this won't be an issue in the future. Thanks!
