### ISSUE TITLE
Swift 4 generate @objc inference warning

### ISSUE THREAD

**Issue by hcstudt** [InderKumarRathore/DeviceGuru#48]
It seems that the use of Swift 3 @objc inference in Swift 4 mode is deprecated.
I get the warning message I recieve:
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "DeviceGuru" target.

**Comment by InderKumarRathore** [comment]
I ran the project and couldn't see the issue can you please send me the sample app.
 Thanks

**Comment by InderKumarRathore** [comment]
Although I was unable to find this issues still I've updated the xcode project, should be fixed in `4.0.5`
