### ISSUE TITLE
Value of type 'Platform' has no member 'rawValue'

### ISSUE THREAD

**Issue by StartCrate** [InderKumarRathore/DeviceGuru#50]
Hi there, I get this error when trying to run the code

DeviceGuru has been imported and installed through cocoapods

This code has been copied pasted across.

The project does also use deignkit but I have not imported it within my viewcontroller so should be fine.

let deviceGuru = DeviceGuru()
let deviceName = deviceGuru.hardware()
let deviceCode = deviceGuru.hardwareString()
let platform = deviceGuru.platform()
print("\(deviceName) - \(deviceCode) - \(platform.rawValue)") //Ex: iphone_7_PLUS - iPhone9,2 - iphone

**Comment by InderKumarRathore** [comment]
This is because Platform enum doesn't have any type (Int or String) thus rawValue is not available to this enum. If you want to print it just use `platform` instead of `platform.rawValue`. e.g.
`print("\(deviceName) - \(deviceCode) - \(platform)")`

**Comment by StartCrate** [comment]
Thank you :)
