### ISSUE TITLE
iPhone11,6 not listed

### ISSUE THREAD

**Issue by over140** [InderKumarRathore/DeviceGuru#55]
I get this console message:

> This is a device which is not listed in this category. Please visit https://github.com/InderKumarRathore/DeviceGuru and add a comment there.
Your device hardware string is: %@ iPhone11,6

**Comment by InderKumarRathore** [comment]
You're using old version,  current pod version is `4.0.5`. The log message you posted belongs to older version new version has little different messaging. Just let me know if this is not the case. Otherwise you can close the issue.

**Comment by over140** [comment]
It's ok!
