### ISSUE TITLE
The hardware string is swapped for the XS Max Global and XS Max China

### ISSUE THREAD

**Issue by gfoldv** [InderKumarRathore/DeviceGuru#58]
According to multiple sources the iPhone11,4 belongs to the XS Max China and the iPhone11,6 belongs to the XS Max Global. I can also confirm that devices used in Germany are reporting iPhone11,6 

https://gist.github.com/adamawolf/3048717
https://www.theiphonewiki.com/wiki/Models

**Comment by InderKumarRathore** [comment]
I need to research more about it, the links provided by you tells that string has been inverted but my simulator XS max is giving 11,4. Give me some time to figure it out.

**Comment by ReesKlintworth** [comment]
https://ipsw.me/otas/iPhone11,6 also shows that iPhone11,6 is global. We're using DeviceGuru in a production app, and have confirmed that non-China market iPhone XS Max devices report as the Chinese model. Any way we can get these switched @InderKumarRathore?

**Comment by InfAspire** [comment]
I believe the best thing to do is just mark them both as XS Max and not mark either variant as China. I created a pull request with the change with some more description of about my thoughts here:
[https://github.com/InderKumarRathore/DeviceGuru/pull/61](https://github.com/InderKumarRathore/DeviceGuru/pull/61)

**Comment by InderKumarRathore** [comment]
@InfAspire thanks for adding base name in the pull request. I would also like to know any use case where Chinese or global is useful
