### ISSUE TITLE
Crash in getDeviceList() if Non-Pod users

### ISSUE THREAD

**Issue by alpennec** [InderKumarRathore/DeviceGuru#6]
Hi,

With the last version 1.3.2, if we don't install using Cocoapods, we need to manually include the DeviceList.plist file. But the app crashes in getDeviceList() because the logic is based on the bundle (introduced in 1.3.2). Can you update your code please?
I had to roll back to 1.3.1 to fix this issue.

Thanks,
Axel

**Comment by InderKumarRathore** [comment]
fixed
