### ISSUE TITLE
device hardware string is|iPad11,3|"

### ISSUE THREAD

**Issue by AKogut91** [InderKumarRathore/DeviceGuru#65]
Hello. Can you please added my device to library. Thanks 
My device hardware string is|iPad11,3|"

**Comment by InderKumarRathore** [comment]
Will update the lib for have all new device string

**Comment by antonioreyna** [comment]
hello, can you please add iphone 11 and 11 pro?

**Comment by vova9** [comment]
Good day! Could you add a new device as was done here to see prices in general: https://github.com/InderKumarRathore/DeviceUtil

**Comment by InderKumarRathore** [comment]
I started working on code generation once that is finished probably this Saturday and then I’ll push. I’m making life easier to automate everything and then we don’t have to update at 4-5 places when new device come. Just run the script and all the code will be generated

**Comment by InderKumarRathore** [comment]
Pushed all new changes, let me know if I missed something
