### ISSUE TITLE
Issue with MacOS App

### ISSUE THREAD

**Issue by ghost** [InderKumarRathore/DeviceGuru#67]
This is really a handy library. While building the app with support for MacOS (Catalina), below issue happens (DeviceGuru is included as pod dependency):

Signing for "DeviceGuru-DeviceGuru" requires a development team. Select a development team in the Signing & Capabilities editor.

Can you help to fix this issue?

**Comment by InderKumarRathore** [comment]
hey thanks for reporting, but it seems your local issue
