### ISSUE TITLE
Would you please add swift package support?

### ISSUE THREAD

**Issue by Horse888** [InderKumarRathore/DeviceGuru#74]
Very nice project, would you please add swift package manager support?

**Comment by InderKumarRathore** [comment]
I thought about it, but seems very low use case. Will do it once I understand how spm works

**Comment by Horse888** [comment]
Thanks in advance! Sometimes cocoa pods is slow. So swift package manager is a good choice.

**Comment by Kaspik** [comment]
@InderKumarRathore I believe the use case would be big, especially including this as a static library for example (to use it also in Extensions etc).

If you wanna learn more about it, sure! if you need help, let me know, I can open PR.

**Comment by InderKumarRathore** [comment]
Hey I had my investigation on this and found that in current release of swift(5.2) we don't have option to add resources in SPM but in coming release (beta) we do have. I'll add the support once Apple releases the GM version of Xcode 12

**Comment by witekbobrowski** [comment]
SPM support was implemented in #80 and is now waiting for approval from maintainer.

**Comment by InderKumarRathore** [comment]
Thanks @witekbobrowski for creating the PR and thanks @ZuYuanZhou for creating this issue. It took long but we did it. 🎉
