### ISSUE TITLE
Project is not compiling - missing files

### ISSUE THREAD

**Issue by minixT** [InderKumarRathore/DeviceGuru#85]
Hi,

it looks like current master doesn't work. When I try to build the project I get this error:

```
/.../DeviceGuru/Sources/DeviceGuru.swift:82:31: error: cannot find type 'Platform' in scope
    public func platform() -> Platform {
                              ^~~~~~~~
/.../DeviceGuru/Sources/DeviceGuru.swift:135:36: error: cannot find type 'DeviceVersion' in scope
    public func deviceVersion() -> DeviceVersion? {
                                   ^~~~~~~~~~~~~
/.../DeviceGuru/Sources/DeviceGuru.swift:180:45: error: cannot find type 'DeviceVersion' in scope
    func getVersion(from string: String) -> DeviceVersion? {
                                            ^~~~~~~~~~~~~
/.../DeviceGuru/Sources/DeviceGuru.swift:38:34: error: type 'Bundle' has no member 'module'
            if let path = Bundle.module.path(forResource: resource, ofType: type) {
                          ~~~~~~ ^~~~~~
```

I found that `Platform.swift` and `DeviceVersion.swift` files are not added to the project.

I'm using Xcode 12.1 and working on the code downloaded directly from the repository.

Thanks

**Comment by InderKumarRathore** [comment]
Hi @minixT I'm able to run it. I downloaded code separately and am able to compile and run. I'm running `Example/DeviceGuruExample.xcodeproj` project
Can you please provide the steps?

**Comment by minixT** [comment]
@InderKumarRathore, I try to build `DeviceGuru.xcodeproj`. I'm just opening this project in Xcode 12.1 and try to build `DeviceGuru` schema. I'm using Carthage to integrate my project with DeviceGuru and now it also doesn't work because Carthage also try to build schema from `DeviceGure.xcodeproj`.

**Comment by InderKumarRathore** [comment]
I see, so for Carthage it's not working. Will fix it. I think I just need to add those files in project.

**Comment by InderKumarRathore** [comment]
can you please check now. i pushed the code

**Comment by minixT** [comment]
I checked and now it works. Thank you!
