### ISSUE TITLE
Missing bundle version when using Carthage

### ISSUE THREAD

**Issue by minixT** [InderKumarRathore/DeviceGuru#89]
Hi,
I was trying to upload an app to AppStore Connect with DeviceGuru framework built using Carthage and I received this error: 

> This bundle Payload/xxx.app/Frameworks/DeviceGuru.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion.

I checked Info.plist in the framework and version was actually missing. I checked also DeviceGuru project and it looks like bundle version is set to `$(CURRENT_PROJECT_VERSION)` but this option is empty in build settings.

Can you fix this by adding some value to  CURRENT_PROJECT_VERSION option in build setting, so I can successfully upload my app.

Thanks

**Comment by InderKumarRathore** [comment]
I added the bundle version `7.0.1` same as pod version. I hope this should work

**Comment by minixT** [comment]
@InderKumarRathore, it looks like it didn't help. I tested this and updating this value only in info.plist is not enough. Only after setting `CURRENT_PROJECT_VERSION` option in build settings I was able to  receive framework with CFBundleVersion.

**Comment by InderKumarRathore** [comment]
Can you please raise a PR?

**Comment by InderKumarRathore** [comment]
fixed

**Comment by minixT** [comment]
Now it works. Thank you!
