### ISSUE TITLE
Crash on DeviceGuru.init()

### ISSUE THREAD

**Issue by bruno-hcr** [InderKumarRathore/DeviceGuru#96]
Hello! 

Basically what's happening is when I'm debugging my application, sometimes this crash occurs. The most part happens when I put a break point in some line of code or try to stop on a break point.

We also discovered that this crash happens on production code some times.

We're testing on simulator (iPhone 11 Pro 14.4)

The lib is up to date on 7.0.1 version, using cocoapods.

<img width="1107" alt="Screen Shot 2021-04-06 at 10 00 05" src="https://user-images.githubusercontent.com/21697643/113730272-1eda8980-96ce-11eb-9264-767d1454b734.png">

**Comment by InderKumarRathore** [comment]
Seems like plist is unable to convert to NSDictionery

**Comment by bruno-hcr** [comment]
This is strange, because it happens few times

**Comment by bruno-hcr** [comment]
Another weird thing it's when I'm trying to print the object exactly equals when crash occurs, it returns a valid object 

<img width="1404" alt="Screen Shot 2021-04-06 at 12 53 21" src="https://user-images.githubusercontent.com/21697643/113740458-163a8100-96d7-11eb-820d-1d0fe7854598.png">

**Comment by InderKumarRathore** [comment]
Are you still facing this issue? As I haven't faced it
